/****************************************************************************
 * examples/pdm_demo/sigproc/resource.h
 *
 *   Copyright 2021 Sony Semiconductor Solutions Corporation
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name of Sony Semiconductor Solutions Corporation nor
 *    the names of its contributors may be used to endorse or promote
 *    products derived from this software without specific prior written
 *    permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

#ifndef __EXAMPLES_SIGPROC_RESOURCE_H
#define __EXAMPLES_SIGPROC_RESOURCE_H

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* These IDs are sharing with dsp */

#define DSP_MQID   10
#define DSP_MQID2  11

/* Determine which is RPC, they are magic numbers. */

#define DSP_RPC_MSG         30
#define DSP_RPC_MSG_ASYNC   31
#define DSP_RPC_RET         40
#define DSP_RPC_UNDEF       41
#define DSP_RPC_UNLOAD      90

/* DSP offload function hashes.
 * These hashes are generated by following commands (by hands!).
 *
 * echo <define name> | sha1sum - | cut -b -8
 *
 * e.g. $ echo DSP_INIT | sha1sum - | cut -b -8
 */

#define DSP_INIT         0x9fe8fc96
#define DSP_DEINIT       0xd74211ec
#define DSP_SET_FFT      0x3c317827
#define DSP_SET_MOTOR    0xe4ad3627
#define DSP_SET_SENSOR   0xb228ede8
#define DSP_EXEC         0xe795da20
#define DSP_RESULT       0xdcdd1fbd
#define DSP_RESET        0x7ffafa19


#define FFT_ATTR_NOTIFY  0x80000000


#endif /* __EXAMPLES_SIGPROC_RESOURCE_H */
